#!/usr/bin/env php
<?php

define('BP', __DIR__);
$vendorAutoload = BP . DIRECTORY_SEPARATOR . "vendor/autoload.php";

/** 'composer install' validation **/
if (!file_exists($vendorAutoload)) {
    throw new \Exception(
        'Vendor autoload is not found. Please run \'composer install\' under application root directory.'
    );

}

require_once $vendorAutoload;

/** Run application */
$app = new RootIndex\Redmine\Lite\Application;
